version: '3.8'

services:
  weather-app-postgres:
    image: postgres:latest
    container_name: weather-app-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: weather_app
    ports:
      - "5432:5432"

  weather-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather-app
    ports:
      - "8080:8080"
    depends_on:
      - weather-app-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://weather-app-postgres:5432/weather_app
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234